### ISSUE TITLE
Have Readme.md up-to-date

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Ruuter#70]
AS AN Interested Party
I WANT TO have `Readme.md` as a single source of truth to cover all of Ruuter's functionalities, guides to set it up and other need-to-knows
SO THAT I could make an informed decision whether to take it into use and if yes, then how to do it

### Acceptance Criteria

- [ ] Following the setup guide ends up with Ruuter being installed locally and being fully functional
- [ ] All functionalities are described with at least 1 sentence and a link to sample DSLs or other YAML files

**Comment by henrikprangelNG** [comment]
@turnerrainer - i personally would prefer if we described all functionalities in some sort of a GUIDE.md or perhaps a GUIDE or SAMPLES folder. Otherwise the readme file would grow in size to be rather huge and annoying to navigate.

Ideally i would make it so that the README file contained all the necessary info for "ruuter setup and configuration", and move all the guides to a "guides folder", where there was a separate `.md` file for every functionality. 

Is this okay with you, or would prefer to keep everything in the readme.md?

**Comment by turnerrainer** [comment]
> @turnerrainer - i personally would prefer if we described all functionalities in some sort of a GUIDE.md or perhaps a GUIDE or SAMPLES folder. Otherwise the readme file would grow in size to be rather huge and annoying to navigate.
> 
> Ideally i would make it so that the README file contained all the necessary info for "ruuter setup and configuration", and move all the guides to a "guides folder", where there was a separate `.md` file for every functionality.
> 
> Is this okay with you, or would prefer to keep everything in the readme.md?

@henrikprangelNG sounds reasonable, let's not overwhelm readme.md with all the samples.
